CREATE DATABASE IF NOT EXISTS BD_SENSORES;
USE BD_SENSORES;

CREATE TABLE IF NOT EXISTS SENSORES(
	SENSOR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	SENSOR_NOME VARCHAR(200) NOT NULL,
    SENSOR_STATUS ENUM('ATIVO', 'INATIVO') NOT NULL
);

CREATE TABLE IF NOT EXISTS MEDIDAS_SENSORES(
	MEDIDA_SENSOR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MEDIDA_SENSOR_DADO VARCHAR(200) NOT NULL,
    MEDIDA_SENSOR_UNIDADE_MEDIDA VARCHAR(200) NOT NULL,
    MEDIDA_SENSOR_DATA DATETIME NOT NULL,
    FK_SENSOR_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_SENSOR_ID) REFERENCES SENSORES(SENSOR_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO SENSORES (SENSOR_NOME, SENSOR_STATUS )
VALUES ("DHT11","ATIVO");

INSERT INTO SENSORES (SENSOR_NOME, SENSOR_STATUS )
VALUES ("HC-SR04","ATIVO");

INSERT INTO SENSORES (SENSOR_NOME, SENSOR_STATUS )
VALUES ("RFID-RC522","ATIVO");

INSERT INTO SENSORES (SENSOR_NOME, SENSOR_STATUS )
VALUES ("MQ-135","ATIVO");

INSERT INTO MEDIDAS_SENSORES (MEDIDA_SENSOR_DADO, MEDIDA_SENSOR_UNIDADE_MEDIDA, MEDIDA_SENSOR_DATA, FK_SENSOR_ID)
VALUES
("23.5","ºC", NOW(), 1), -- TEMPERATURA - DHT11
("50","%", NOW(), 1), -- UMIDADE - DHT11
("50","cm", NOW(), 2), -- DISTÂNCIA - HC-SR04
("1300","ppm", NOW(), 4); -- GÁS - MQ-135